//defines.h
#ifndef _DEFINES_H
#define _DEFINES_H

#define SETBIT(WORD,BITPOS) (WORD |= (1<<BITPOS))
#define CLRBIT(WORD,BITPOS) (WORD &= ~(1<<BITPOS))
#define CPLBIT(WORD,BITPOS) (WORD ^= (1<<BITPOS))
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)

#define SSETBIT(WORD,BITPOS) (WORD = 1<<BITPOS)	//used for IOSET SFR
#define SCLRBIT(WORD,BITPOS)  (WORD = 1<<BITPOS)	//used for IOCLR SFR

#define WRITEBYTE(WORD,SBITPOS,DATA) \
(WORD = ((WORD&~(255<<SBITPOS)) | (DATA<<SBITPOS)))

#define WRITEBIT(WORD,BITPOS,BITVAL) \
(WORD = ((WORD&~(1<<BITPOS)) | (BITVAL<<BITPOS)))

#define READWRITEBIT(DWORD,WBIT,SWORD,RBIT) \
(DWORD=(DWORD&~(1<<WBIT))|(((SWORD>>RBIT)&1)<<WBIT))
#define CFGPIN(WORD,PINNO,FUNC) \
(WORD=(PINN0<16)?(WORD &~(3<<(PININ0*2)))|(FUNC<<(PINNO*2)):(WORD &~(3<<((PININ0-16)*2)))|(FUNC<<((PINNO-16)*2))

#endif
