//defines.h
#ifndef _DEFINES_H
#define _DEFINES_H

#define SETBIT(WORD,BITPOS) (WORD |= (1<<BITPOS))
#define CLRBIT(WORD,BITPOS) (WORD &= ~(1<<BITPOS))
#define CPLBIT(WORD,BITPOS) (WORD ^= (1<<BITPOS))


#define SSETBIT(WORD,BITPOS) (WORD = 1<<BITPOS)	//used for IOSET SFR
#define SCLRBIT SSETBIT	//used for IOCLR SFR

#define WRITEBYTE(WORD,SBITPOS,DATA) \
(WORD = ((WORD&~(255<<SBITPOS)) | (DATA<<SBITPOS)))

#define WRITENIBBLE(WORD,SBITPOS,DATA) \
(WORD = ((WORD&~(15<<SBITPOS)) | (DATA<<SBITPOS)))

#define WRITEBIT(WORD,BITPOS,BITVAL) \
(WORD = ((WORD&~(1<<BITPOS)) | (BITVAL<<BITPOS)))

#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define READNIBBLE(WORD,SBITPOS) ((WORD>>SBITPOS)&15)
#define READBYTE(WORD,SBITPOS) ((WORD>>SBITPOS)&255)

#endif
